name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    uses: devantler-tech/reusable-workflows/.github/workflows/release.yaml@2524366fcc9f60e130ee3c423b2cc83ffd1e814d # v1.2.6
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
